### ISSUE TITLE
[New Feature] Support securitySchemes

### ISSUE THREAD

**Issue by luolingchun** [0b01001001/spectree#121]
I am using JWT token in OpenAPI.
I understand that **`securityschemes`** defines security schemes. Please consider adding **`securityschemes`** in **`Components object`**

https://github.com/0b01001001/spectree/blob/v0.4.2/spectree/spec.py#L236

```python
spec = {
            "openapi": self.config.OPENAPI_VERSION,
            "info": {
                "title": self.config.TITLE,
                "version": self.config.VERSION,
                "description": self.config.DESCRIPTION,
            },
            "tags": list(tags.values()),
            "paths": {**routes},
            "components": {"schemas": {**self.models, **self._get_model_definitions()}},
        }
```
just like:

```yaml
components:
  schemas:
     ...
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
}
```
